name: CI/CD Pipeline - Node.js Demo App

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

                 # Log in to DockerHub
      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Export DockerHub username cleanly
      - name: Set DockerHub Username
        run: echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV

      # Build Docker image
      - name: Build Docker Image
        run: docker buildx build -t "$DOCKERHUB_USERNAME/nodejs-demo-app:latest" --load .

      # Push Docker image
      - name: Push Docker Image
        run: docker push "$DOCKERHUB_USERNAME/nodejs-demo-app:latest"
